# Generated by Django 5.0.9 on 2024-11-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='login',
            name='updated_at',
        ),
    ]
