# Generated by Django 5.0.9 on 2024-11-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_login_date_joined_login_groups_login_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_permissions',
        ),
    ]
