# Generated by Django 5.0.9 on 2024-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_login_date_joined_remove_login_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
