# Generated by Django 5.0.10 on 2024-12-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
        migrations.AlterModelTable(
            name='appointmentstate',
            table='appointment_state',
        ),
        migrations.AlterModelTable(
            name='clinician',
            table='Clinician',
        ),
        migrations.AlterModelTable(
            name='cliniciangroup',
            table='Clinician_groups',
        ),
        migrations.AlterModelTable(
            name='clinicianlocation',
            table='Clinician_location',
        ),
        migrations.AlterModelTable(
            name='clinicianmodality',
            table='Clinician_modalities',
        ),
        migrations.AlterModelTable(
            name='clinicianspeciality',
            table='Clinician_specialities',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
        migrations.AlterModelTable(
            name='modality',
            table='Modalities',
        ),
        migrations.AlterModelTable(
            name='speciality',
            table='Specialities',
        ),
    ]
