# Generated by Django 5.0.10 on 2024-12-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0002_alter_appointment_table_alter_appointmentstate_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('login_id', models.CharField(max_length=255, unique=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.clinician')),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
    ]
