# Generated by Django 5.0.10 on 2024-12-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('EVENT', 'Event'), ('OUT_OF_OFFICE', 'Out of Office')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'EventType',
            },
        ),
        migrations.AddField(
            model_name='clinician',
            name='color',
            field=models.CharField(default='#7499e1', max_length=7),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('cancel_appointments', models.BooleanField(default=False)),
                ('notify_clients', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.clinician')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.location')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.patient')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.appointmentstate')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinician_dashboard.eventtype')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'start_time'], name='Event_start_d_614e87_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['clinician', 'start_date'], name='Event_clinici_5eb2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type', 'start_date'], name='Event_type_id_01cde6_idx'),
        ),
    ]
