# Generated by Django 5.0.10 on 2024-12-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0004_eventtype_clinician_color_event_delete_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
