# Generated by Django 5.0.10 on 2024-12-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0005_clinician_first_name_clinician_last_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='Event_start_d_614e87_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='Event_clinici_5eb2b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='Event_type_id_01cde6_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='America/Chicago', max_length=50),
        ),
    ]
