# Generated by Django 5.0.10 on 2024-12-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0006_remove_event_event_start_d_614e87_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
