# Generated by Django 5.0.10 on 2024-12-11 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0007_remove_event_timezone_alter_event_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
