# Generated by Django 5.0.10 on 2024-12-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0008_event_occurrence_date_event_parent_event_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clinician',
            index=models.Index(fields=['login_id'], name='Clinician_login_i_ba2912_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='Event_start_d_ab71be_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['clinician'], name='Event_clinici_6d11ce_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='Event_type_id_2a0105_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['parent_event'], name='Event_parent__86937f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_recurring'], name='Event_is_recu_0587c9_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['login_id'], name='Patient_login_i_2bb5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinician'], name='Patient_clinici_1c5636_idx'),
        ),
    ]
