# Generated by Django 5.0.10 on 2024-12-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0009_clinician_clinician_login_i_ba2912_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member_events', to='clinician_dashboard.clinician'),
        ),
        migrations.AlterField(
            model_name='event',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_events', to='clinician_dashboard.clinician'),
        ),
    ]
