# Generated by Django 5.0.10 on 2024-12-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0011_alter_appointmentstate_id_alter_clinician_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PracticeService',
            },
        ),
    ]
