# Generated by Django 5.0.10 on 2024-12-22 00:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0012_practiceservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinician_dashboard.practiceservice'),
        ),
        migrations.AddField(
            model_name='practiceservice',
            name='duration',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClinicianService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_rate', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.clinician')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.practiceservice')),
            ],
            options={
                'db_table': 'Clinician_services',
                'indexes': [models.Index(fields=['clinician'], name='Clinician_s_clinici_f02526_idx'), models.Index(fields=['service'], name='Clinician_s_service_8bd3cf_idx')],
                'unique_together': {('clinician', 'service')},
            },
        ),
        migrations.CreateModel(
            name='PatientDefaultService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_rate', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.practiceservice')),
            ],
            options={
                'db_table': 'Patient_default_services',
                'indexes': [models.Index(fields=['patient'], name='Patient_def_patient_a185f4_idx'), models.Index(fields=['service'], name='Patient_def_service_1e841e_idx')],
                'unique_together': {('patient', 'service')},
            },
        ),
    ]
