# Generated by Django 5.0.10 on 2024-12-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0013_event_service_practiceservice_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.clinician'),
        ),
    ]
