# Generated by Django 5.0.10 on 2024-12-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0014_alter_patient_clinician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='service',
        ),
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.event')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.practiceservice')),
            ],
            options={
                'db_table': 'Event_services',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='events', through='clinician_dashboard.EventService', to='clinician_dashboard.practiceservice'),
        ),
        migrations.AddIndex(
            model_name='eventservice',
            index=models.Index(fields=['event'], name='Event_servi_event_i_05b7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventservice',
            index=models.Index(fields=['service'], name='Event_servi_service_304e36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventservice',
            unique_together={('event', 'service')},
        ),
    ]
