# Generated by Django 5.0.10 on 2024-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0015_remove_event_service_eventservice_event_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='appointment_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
