# Generated by Django 5.0.10 on 2024-12-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0016_event_appointment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventservice',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='modifiers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
