# Generated by Django 5.0.10 on 2024-12-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0019_remove_appointmentstate_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'NoteTemplate',
                'indexes': [models.Index(fields=['is_active'], name='NoteTemplat_is_acti_4667d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.clinician')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notes', to='clinician_dashboard.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinician_dashboard.notetemplate')),
            ],
            options={
                'db_table': 'EventNote',
                'indexes': [models.Index(fields=['event'], name='EventNote_event_i_6b88fa_idx'), models.Index(fields=['created_by'], name='EventNote_created_915b68_idx'), models.Index(fields=['created_at'], name='EventNote_created_51c409_idx')],
            },
        ),
    ]
