# Generated by Django 5.0.10 on 2024-12-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0020_notetemplate_eventnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Note_template_type',
            },
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinician_dashboard.notetemplatetype'),
        ),
    ]
