# Generated by Django 5.0.10 on 2024-12-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0021_notetemplatetype_notetemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplatetype',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
