# Generated by Django 5.0.10 on 2025-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0022_notetemplatetype_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
