# Generated by Django 5.0.10 on 2025-01-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0024_alter_eventnote_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventservice',
            unique_together=set(),
        ),
    ]
