# Generated by Django 5.0.10 on 2025-01-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0025_alter_eventservice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhsycotherapyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.clinician')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phsycotherapy_notes', to='clinician_dashboard.event')),
            ],
            options={
                'db_table': 'PhsycotherapyNote',
                'indexes': [models.Index(fields=['event'], name='Phsycothera_event_i_971437_idx'), models.Index(fields=['created_by'], name='Phsycothera_created_8d605a_idx')],
            },
        ),
    ]
