# Generated by Django 5.0.10 on 2025-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0026_phsycotherapynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phsycotherapynote',
            name='note_data',
            field=models.TextField(),
        ),
    ]
