# Generated by Django 5.0.10 on 2025-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0027_alter_phsycotherapynote_note_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
