# Generated by Django 5.0.10 on 2025-01-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0028_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='color',
            field=models.CharField(default='#7499e1', max_length=7),
        ),
    ]
