# Generated by Django 5.0.10 on 2025-01-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0029_location_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_member',
        ),
        migrations.AlterField(
            model_name='event',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_events', to='clinician_dashboard.clinician'),
        ),
    ]
