# Generated by Django 5.0.10 on 2025-01-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0030_remove_event_team_member_alter_event_clinician'),
    ]

    operations = [
          ]
