# Generated by Django 5.0.10 on 2025-01-08 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_dashboard', '0031_careteam_remove_patient_patient_clinici_1c5636_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CareTeam',
            },
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='Patient_clinici_1c5636_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='clinician',
        ),
        migrations.AddField(
            model_name='careteam',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.clinician'),
        ),
        migrations.AddField(
            model_name='careteam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_dashboard.patient'),
        ),
        migrations.AddField(
            model_name='clinician',
            name='patients',
            field=models.ManyToManyField(through='clinician_dashboard.CareTeam', to='clinician_dashboard.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinicians',
            field=models.ManyToManyField(through='clinician_dashboard.CareTeam', to='clinician_dashboard.clinician'),
        ),
        migrations.AddIndex(
            model_name='careteam',
            index=models.Index(fields=['patient', 'clinician'], name='CareTeam_patient_f96bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='careteam',
            index=models.Index(fields=['is_primary'], name='CareTeam_is_prim_599c98_idx'),
        ),
        migrations.AddIndex(
            model_name='careteam',
            index=models.Index(fields=['status'], name='CareTeam_status_2da6f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careteam',
            unique_together={('patient', 'clinician')},
        ),
    ]
